tap "buo/cask-upgrade"
# CLI tools
brew "bat"
brew "ffmpeg"
brew "glib"
brew "imagemagick"
brew "mas"
brew "rpm"
brew "snapcraft"
brew "starship"
brew "trash"
brew "wget"
brew "wine"
brew "zlib"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# Cask apps
cask "visual-studio-code"
cask "angry-ip-scanner"
cask "cursor"
cask "cyberduck"
cask "docker"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "gimp"
# cask "inkscape"
cask "ngrok"
# cask "postman"
cask "slack"
cask "spotify"
cask "transmission"
cask "unetbootin"
# cask "vagrant"
cask "vlc"
cask "virtualbox"
cask "warp"
cask "xquartz"
cask "zed"
cask "zoom"

# QuickLook plugins
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlprettypatch"
cask "quicklook-csv"
cask "betterzipql"
cask "webpquicklook"
cask "suspicious-package"
cask "syntax-highlight"
cask "qlvideo"

# Mac App Store apps
mas "Amphetamine", id: 937984704
# mas "BetterSnapTool", id: 417375580
mas "Flycut", id: 442160987
